<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <!-- Standard Framework Assets -->
    <EmbeddedResource Include="Fonts\**\*"/>
    <EmbeddedResource Include="Samples\**\*"/>
    <EmbeddedResource Include="Textures\**\*"/>
    <EmbeddedResource Include="Tracks\**\*"/>
    <EmbeddedResource Include="Translations\**\*"/>
    <EmbeddedResource Include="Shaders\**\*"/>
  </ItemGroup>

  <ItemGroup>
    <!-- Embed custom assets without copying them to the output folder -->
    <EmbeddedResource Include="funfacts.json" />
    <EmbeddedResource Include="Webapp\**\*" />
    <EmbeddedResource Include="Video\**\*" />
  </ItemGroup>

  <ItemGroup>
    <Reference Include="osu.Framework">
      <HintPath>..\..\..\.nuget\packages\ppy.osu.framework\2026.513.0\lib\net8.0\osu.Framework.dll</HintPath>
    </Reference>
  </ItemGroup>
</Project>
